parser:                              babel-eslint

extends:
- airbnb
- plugin:flowtype/recommended
- plugin:css-modules/recommended
- prettier
- prettier/flowtype
- prettier/react
plugins:
- flowtype
- css-modules
- prettier
globals:
  __DEV__:                           true
env:
  browser:                           true
rules:
  indent:
  - 2
  - tab
  - SwitchCase:                      1
  no-underscore-dangle:              'off'
  quotes:
  - error
  - double
  - avoidEscape:                     true
  jsx-quotes:
  - error
  - prefer-double
  import/extensions:
  - error
  - always
  - js:                              never
    jsx:                             never
    mjs:                             never
  import/no-extraneous-dependencies: 'off'
  no-console:
  - error
  - allow:
    - warn
    - error
    - info
  jsx-a11y/href-no-hash:             'off'
  jsx-a11y/label-has-for:            warn
  react/jsx-filename-extension:
  - error
  - extensions:
    - ".js"
    - ".jsx"
  react/prefer-stateless-function:   'off'
  prettier/prettier:
  - error
  - tabWidth:                        1
    useTabs:                         true
    singleQuote:                     false
    trailingComma:                   none
settings:
  import/resolver:
    node:
      moduleDirectory:
      - node_modules
      - src
